# STS role and target account
Sts.Role: arn:aws:iam::398099758646:role/Admin

# Stack settings
Stack.Name: microtrader-production
Stack.Description: Microtrader Stack - Production

# Override all deletion policies of type AWS::RDS::DBInstance
AWS::RDS::DBInstance:
  DeletionPolicy: Delete

# Override all deletion policies of type AWS::Logs::LogGroup
AWS::Logs::LogGroup:
  DeletionPolicy: Delete

# Microtrader settings
Stack.Inputs.MicrotraderQuoteHttpPort: 8000
Stack.Inputs.MicrotraderAuditHttpPort: 8001
Stack.Inputs.MicrotraderDashboardHttpPort: 8002

# Database settings
Stack.Inputs.DatabaseName: audit
Stack.Inputs.DatabaseUsername: audit
Stack.Inputs.DatabasePassword: AQICAHhWGc7thollN6f7zbhA0gIJLbqZuXClFf2SKmIcZaTB3AGWRh+J5DzPy6Yv3olUMORRAAAAczBxBgkqhkiG9w0BBwagZDBiAgEAMF0GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM78X9YQxG0AAZ71RmAgEQgDDLeazAs4iP1ICjGCbx1DQQ7keeMCnW24L0mV6Ia8AvrNzHFlXT1keuaumcWntEHZE=
# Application settings
Stack.Inputs.ApplicationDnsName: prod-microtrader
Stack.Inputs.ApplicationImageId: ami-0a6e79fab362a22d0
Stack.Inputs.ApplicationKeyName: admin


Stack.Inputs.EcsTaskRunnerVersion: KD2o3T.4Symh85Y71HGXfIxSHDvQ3MLS
